# Generated by Django 2.2.14 on 2020-07-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200728_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='datos_personales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Persona'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Municipio'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Medico'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='datos_personales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Persona'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='entidad_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Entidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Especialidad'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Departamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Municipio'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='historial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.HistoriaClinica'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='lista_medicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Receta'),
        ),
    ]
