# Generated by Django 2.2.14 on 2020-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200728_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(default='0011122', max_length=8),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(default='00111222', max_length=8),
        ),
    ]
